export type TemplateType =
  | 'Landing'
  | 'Story'
  | 'Pricing'
  | 'Role'
  | 'Directory'
  | 'Integration'
  | 'Comparison'
  | 'Changelog'
  | 'Company'
  | 'Hub'
  | 'Article'
  | 'Docs'
  | 'Help'
  | 'Trust'
  | 'Status'
  | 'Careers'
  | 'Form'
  | 'System'
  | 'App';

export type TierType = 1 | 2 | 3 | 'App';
export type RouteStatus = 'planned' | 'built' | 'verified';

export interface RouteManifestEntry {
  path: string;
  template: TemplateType;
  tier: TierType;
  originalUrl: string;
  title: string;
  description: string;
  status: RouteStatus;
  notes?: string;
}

export const ROUTE_MANIFEST: RouteManifestEntry[] = [
  // TIER 1: MARKETING & CORE DIRECTORIES
  {
    path: '/',
    template: 'Landing',
    tier: 1,
    originalUrl: 'https://fathom.ai/',
    title: 'Fathom (rebuild) — The AI Meeting Assistant with Receipts',
    description: 'Shockingly accurate notes and transcripts with clickable timecode receipts jumping to the spoken moment. Used by high-performance teams.',
    status: 'verified',
    notes: 'Interactive hero meeting fixture with live playhead, audio clock, and receipt-backed summary tabs.',
  },
  {
    path: '/overview',
    template: 'Story',
    tier: 1,
    originalUrl: 'https://fathom.ai/overview',
    title: 'Product Story & Lifecycle Overview | Fathom',
    description: 'Experience meeting intelligence across the complete conversation lifecycle: Before, During, After, and Later.',
    status: 'built',
    notes: 'Scroll narrative showing real app components in sequence, replacing repetitious marketing pages.',
  },
  {
    path: '/pricing',
    template: 'Pricing',
    tier: 1,
    originalUrl: 'https://fathom.ai/pricing',
    title: 'Transparent Pricing & Plans | Fathom',
    description: 'Unlimited recordings for free. Scaled plans with AI summaries, custom templates, CRM sync, and SOC2 compliance. All sample prices clearly labeled.',
    status: 'built',
    notes: 'Includes audience toggle, sticky comparison matrix, 3-question plan finder, and enterprise contact modal.',
  },
  {
    path: '/solutions/sales',
    template: 'Role',
    tier: 1,
    originalUrl: 'https://fathom.ai/solutions/sales',
    title: 'Fathom for Sales Teams — Auto-fill CRM & Win Deals',
    description: 'Automatically log call notes, objections, and next steps into Salesforce and HubSpot with zero rep overhead.',
    status: 'built',
    notes: 'MEDDIC-style deal review fixture, saved prompt pills, and CRM webhook payloads.',
  },
  {
    path: '/solutions/customer-success',
    template: 'Role',
    tier: 1,
    originalUrl: 'https://fathom.ai/solutions/customer-success',
    title: 'Fathom for Customer Success — Retention & QBR Recaps',
    description: 'Capture renewals, feature requests, and customer sentiment automatically from every touchpoint.',
    status: 'built',
  },
  {
    path: '/solutions/marketing',
    template: 'Role',
    tier: 1,
    originalUrl: 'https://fathom.ai/solutions/marketing',
    title: 'Fathom for Marketing — Voice of Customer & Research',
    description: 'Turn customer discovery calls into product quotes, testimonial clips, and messaging insights.',
    status: 'built',
  },
  {
    path: '/solutions/teams',
    template: 'Role',
    tier: 1,
    originalUrl: 'https://fathom.ai/solutions/teams',
    title: 'Fathom for Cross-Functional Teams — Shared Intelligence',
    description: 'Eliminate update syncs with searchable knowledge, instant catch-up clips, and shared workspace visibility.',
    status: 'built',
  },
  {
    path: '/solutions/operations',
    template: 'Role',
    tier: 1,
    originalUrl: 'https://fathom.ai/solutions/operations',
    title: 'Fathom for Operations & RevOps — Process Consistency',
    description: 'Enforce standard qualification fields and sync structured data cleanly into your operational tools.',
    status: 'built',
  },
  {
    path: '/solutions/engineering',
    template: 'Role',
    tier: 1,
    originalUrl: 'https://fathom.ai/solutions/engineering',
    title: 'Fathom for Engineering & Product — Bug & Spec Sync',
    description: 'Bridge customer bug reports directly into Linear and Jira with exact spoken audio snippets.',
    status: 'built',
  },
  {
    path: '/integrations',
    template: 'Directory',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations',
    title: 'Integrations Directory — Connect Your Entire Stack | Fathom',
    description: 'Seamlessly sync meeting recaps, action items, and clips with 21+ supported tools including Salesforce, HubSpot, Slack, and Notion.',
    status: 'built',
    notes: 'Instant category & plan filtering with URL state, search bar, and empty states.',
  },
  {
    path: '/integrations/category/:slug',
    template: 'Directory',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations-crm',
    title: 'Integrations by Category | Fathom',
    description: 'Filter Fathom integrations by CRM, project management, collaboration, video conferencing, and automation.',
    status: 'built',
  },
  {
    path: '/integrations/salesforce',
    template: 'Integration',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations/salesforce',
    title: 'Salesforce Integration — Automated Call Logging | Fathom',
    description: 'Automatically populate Opportunity fields, Contact records, and Tasks directly from call dialogue.',
    status: 'built',
  },
  {
    path: '/integrations/hubspot',
    template: 'Integration',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations/hubspot',
    title: 'HubSpot Integration — Clean CRM Sync | Fathom',
    description: 'Sync customer deals, timeline events, and action items into HubSpot CRM without human effort.',
    status: 'built',
  },
  {
    path: '/integrations/slack',
    template: 'Integration',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations/slack',
    title: 'Slack Integration — Instant Meeting Digests | Fathom',
    description: 'Broadcast summary highlights and action items into dedicated Slack channels as soon as meetings finish.',
    status: 'built',
  },
  {
    path: '/integrations/notion',
    template: 'Integration',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations/notion',
    title: 'Notion Integration — Centralize Meeting Knowledge | Fathom',
    description: 'Send structured meeting databases, action checklists, and transcripts into Notion team workspaces.',
    status: 'built',
  },
  {
    path: '/integrations/asana',
    template: 'Integration',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations/asana',
    title: 'Asana Integration — Action Items to Tasks | Fathom',
    description: 'Turn verbal commitments from meetings directly into assigned Asana project tasks with timestamps.',
    status: 'built',
  },
  {
    path: '/integrations/zapier',
    template: 'Integration',
    tier: 1,
    originalUrl: 'https://fathom.ai/integrations/zapier',
    title: 'Zapier Integration — Connect 5,000+ Apps | Fathom',
    description: 'Trigger automated workflows whenever a meeting finishes, a highlight is pinned, or action items are created.',
    status: 'built',
  },
  {
    path: '/whats-new',
    template: 'Changelog',
    tier: 1,
    originalUrl: 'https://fathom.ai/whats-new',
    title: "What's New — Product Updates & Changelog | Fathom",
    description: 'Track the latest features, engine upgrades, integrations, and performance improvements shipped by Fathom.',
    status: 'built',
    notes: '12+ dated entries with live "Try it in demo" deep links and category filters.',
  },

  // TIER 2: COMPARISONS, HUBS, DOCS, HELP, TRUST, LEGAL
  {
    path: '/about-us',
    template: 'Company',
    tier: 2,
    originalUrl: 'https://fathom.ai/about-us',
    title: 'About Us — Rebuilding Meeting Intelligence | Fathom',
    description: 'Our mission to eliminate manual meeting overhead and provide truthful, receipt-backed conversational intelligence.',
    status: 'built',
  },
  {
    path: '/brand',
    template: 'Company',
    tier: 2,
    originalUrl: 'https://fathom.ai/brand',
    title: 'Brand Assets & Media Press Kit | Fathom',
    description: 'Download official vector logos, tally mark badges, color swatches, and high-resolution interface graphics.',
    status: 'built',
  },
  {
    path: '/vs',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs',
    title: 'Compare Fathom to Other AI Notetakers | Fathom',
    description: 'Side-by-side comparison of Fathom vs Fireflies, Granola, Gong, Otter, and built-in conferencing tools.',
    status: 'built',
  },
  {
    path: '/vs/fireflies',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/fireflies',
    title: 'Fathom vs Fireflies.ai — Honest Comparison',
    description: 'See how Fathom compares on receipt verification, speaker lanes, bot-free capture, and CRM accuracy. Sample comparison.',
    status: 'built',
  },
  {
    path: '/vs/granola',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/granola',
    title: 'Fathom vs Granola — Notetaker Comparison',
    description: 'Evaluating notepad-first workflows versus full multi-speaker playback, receipts, and CRM automation.',
    status: 'built',
  },
  {
    path: '/vs/gong',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/gong',
    title: 'Fathom vs Gong — Revenue Intelligence Comparison',
    description: 'High-speed team capture vs heavyweight enterprise revenue intelligence suite. Sample analysis.',
    status: 'built',
  },
  {
    path: '/vs/otter',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/otter',
    title: 'Fathom vs Otter.ai — Meeting Assistant Comparison',
    description: 'Comparison of transcript speed, speaker lane timelines, privacy standards, and team sharing models.',
    status: 'built',
  },
  {
    path: '/vs/read-ai',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/read-ai',
    title: 'Fathom vs Read.ai — Feature & Privacy Comparison',
    description: 'Compare participant experience, bot presence, executive summaries, and action item reliability.',
    status: 'built',
  },
  {
    path: '/vs/zoom',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/zoom',
    title: 'Fathom vs Zoom AI Companion — Dedicated Notetaking',
    description: 'Why multi-platform teams use Fathom across Zoom, Meet, and Teams with unified CRM workflows.',
    status: 'built',
  },
  {
    path: '/vs/google-meet',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/google-meet',
    title: 'Fathom vs Google Meet Gemini Notes',
    description: 'Comparing ecosystem-locked AI notes with cross-platform CRM sync and clickable receipts.',
    status: 'built',
  },
  {
    path: '/vs/built-in',
    template: 'Comparison',
    tier: 2,
    originalUrl: 'https://fathom.ai/vs/built-in',
    title: 'Fathom vs Built-in Conference Recording Tools',
    description: 'A breakdown of why native video recordings fall short on search, action accountability, and intelligence.',
    status: 'built',
  },
  {
    path: '/resource-hub',
    template: 'Hub',
    tier: 2,
    originalUrl: 'https://fathom.ai/resource-hub',
    title: 'Resource Hub — Guides, Case Studies & Research | Fathom',
    description: 'Curated playbooks, customer stories, workflow templates, and meeting intelligence best practices.',
    status: 'built',
  },
  {
    path: '/case-studies/blackthorn',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/case-studies/blackthorn',
    title: 'Sample Case Study: Blackthorn — RevOps Automation | Fathom',
    description: 'How an agile operations team saved 12 hours per rep per week with automated CRM sync. Sample story.',
    status: 'built',
  },
  {
    path: '/case-studies/bluleadz',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/case-studies/bluleadz',
    title: 'Sample Case Study: Bluleadz — Agency Client Hand-offs | Fathom',
    description: 'Accelerating client onboarding clarity and reducing recap churn by 65%. Sample story.',
    status: 'built',
  },
  {
    path: '/case-studies/ncsi',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/case-studies/ncsi',
    title: 'Sample Case Study: NCSI — Enterprise Diarization at Scale | Fathom',
    description: 'Deploying secure, bot-free meeting intelligence across 500+ consultants. Sample story.',
    status: 'built',
  },
  {
    path: '/learn',
    template: 'Hub',
    tier: 2,
    originalUrl: 'https://fathom.ai/learn',
    title: 'Meeting Intelligence Academy & Guides | Fathom',
    description: 'In-depth articles and operational frameworks for modern distributed meetings and conversation intelligence.',
    status: 'built',
  },
  {
    path: '/learn/meeting-intelligence-playbook',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/learn/meeting-intelligence-playbook',
    title: 'The Modern Meeting Intelligence Playbook (2026)',
    description: 'A comprehensive 800-word field guide to asynchronous recaps, speaker accountability, and timecode receipts.',
    status: 'built',
  },
  {
    path: '/learn/sales-pipeline-hygiene',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/learn/sales-pipeline-hygiene',
    title: 'Automating Sales Pipeline Hygiene Without Rep Friction',
    description: 'How engineering and RevOps leaders use structured meeting extraction to keep CRM data 100% current.',
    status: 'built',
  },
  {
    path: '/learn/executive-recaps-guide',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/learn/executive-recaps-guide',
    title: 'Crafting High-Signal Executive Recaps in 60 Seconds',
    description: 'How to structure bulleted takeaways that VP and C-level stakeholders actually read and act upon.',
    status: 'built',
  },
  {
    path: '/learn/remote-team-synchronization',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/learn/remote-team-synchronization',
    title: 'Asynchronous Synchronization for Cross-Timezone Teams',
    description: 'Replacing marathon standup syncs with 90-second chapter clips and verified action items.',
    status: 'built',
  },
  {
    path: '/partner-programs',
    template: 'Hub',
    tier: 2,
    originalUrl: 'https://fathom.ai/partner-programs',
    title: 'Fathom Partner Ecosystem & Affiliate Programs',
    description: 'Grow your business with Fathom. Solutions partner track, tech integration program, and portfolio credits.',
    status: 'built',
  },
  {
    path: '/program/solution-partners',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/program/solution-partners',
    title: 'Solution Partner Program — Agencies & Consultants | Fathom',
    description: 'Deliver cutting-edge meeting AI and CRM automation to your clients with dedicated partner rev-share.',
    status: 'built',
  },
  {
    path: '/program/integration-partners',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/program/integration-partners',
    title: 'Technology & Integration Partners — Build on Fathom',
    description: 'Integrate your SaaS platform with Fathoms REST API, webhook events, and OAuth2 app directory.',
    status: 'built',
  },
  {
    path: '/program/points-program',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/program/points-program',
    title: 'Fathom Points & Referral Rewards Program',
    description: 'Earn points for inviting colleagues and clients. Redeem points for custom templates and subscription credits.',
    status: 'built',
  },
  {
    path: '/program/portfolio-partners',
    template: 'Article',
    tier: 2,
    originalUrl: 'https://fathom.ai/program/portfolio-partners',
    title: 'Venture & Accelerator Portfolio Credits Program | Fathom',
    description: 'Exclusive meeting intelligence credits for early-stage portfolio startups and incubator cohorts.',
    status: 'built',
  },

  // DEVELOPERS HUB
  {
    path: '/developers',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/',
    title: 'Fathom Developer Hub — API Reference, Webhooks & SDKs',
    description: 'Build custom meeting workflows with the Fathom REST API, real-time webhooks, Model Context Protocol (MCP), and SDKs.',
    status: 'built',
  },
  {
    path: '/developers/quickstart',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/quickstart',
    title: 'Developer Quickstart — 5 Minute API Integration | Fathom',
    description: 'Generate your API key, make your first test request, and inspect meeting summary payloads in minutes.',
    status: 'built',
  },
  {
    path: '/developers/reference',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/api-reference',
    title: 'REST API Reference (12+ Endpoints) | Fathom',
    description: 'Interactive API documentation with curl, TypeScript, and Python code snippets for meetings, summaries, and clips.',
    status: 'built',
  },
  {
    path: '/developers/webhooks',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/webhooks',
    title: 'Webhooks & Event Subscriptions | Fathom',
    description: 'Receive instantaneous HTTP POST payloads when meetings finish, recordings are uploaded, or highlights are pinned.',
    status: 'built',
  },
  {
    path: '/developers/sdks',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/sdks',
    title: 'Official SDKs — TypeScript, Python, and Go | Fathom',
    description: 'Typed client libraries with automatic token refresh, retries, and comprehensive TypeScript types.',
    status: 'built',
  },
  {
    path: '/developers/oauth',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/oauth',
    title: 'OAuth 2.0 Authentication & Scopes | Fathom',
    description: 'Secure authorization flow for building marketplace apps with user and organization-level permissions.',
    status: 'built',
  },
  {
    path: '/developers/mcp',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/mcp',
    title: 'Model Context Protocol (MCP) Server | Fathom',
    description: 'Connect LLM agents (Claude Desktop, Antigravity, Cursor) directly to your meeting knowledge base.',
    status: 'built',
  },
  {
    path: '/developers/examples',
    template: 'Docs',
    tier: 2,
    originalUrl: 'https://developers.fathom.ai/examples',
    title: 'Community Code Examples & Recipes | Fathom',
    description: 'Production-ready scripts for CRM synchronization, daily standup digests, and automated clip compilation.',
    status: 'built',
  },

  // HELP CENTER
  {
    path: '/help',
    template: 'Help',
    tier: 2,
    originalUrl: 'https://help.fathom.video/',
    title: 'Fathom Help Center & Knowledge Base',
    description: 'Guides, FAQs, and step-by-step documentation across all 9 core Fathom categories.',
    status: 'built',
  },
  {
    path: '/help/category/:slug',
    template: 'Help',
    tier: 2,
    originalUrl: 'https://help.fathom.video/category/getting-started',
    title: 'Help Articles by Category | Fathom Support',
    description: 'Browse articles organized by onboarding, call recording, summary templates, integrations, and troubleshooting.',
    status: 'built',
  },
  {
    path: '/help/article/:slug',
    template: 'Help',
    tier: 2,
    originalUrl: 'https://help.fathom.video/articles/bot-vs-bot-free',
    title: 'Knowledge Base Article | Fathom Support',
    description: 'Step-by-step guide with screenshots, troubleshooting checks, and helpful feedback options.',
    status: 'built',
  },
  {
    path: '/help/contact',
    template: 'Help',
    tier: 2,
    originalUrl: 'https://help.fathom.video/contact',
    title: 'Contact Support & Concierge Assistance | Fathom',
    description: 'Reach our team directly for configuration assistance, enterprise onboarding, or technical questions.',
    status: 'built',
  },

  // TRUST, STATUS & LEGAL
  {
    path: '/trust',
    template: 'Trust',
    tier: 2,
    originalUrl: 'https://trust.fathom.video/',
    title: 'Trust & Security Center | Fathom',
    description: 'Enterprise data protection, encryption standards, subprocessor transparency, and compliance architecture. Sample demo notice.',
    status: 'built',
  },
  {
    path: '/status',
    template: 'Status',
    tier: 3,
    originalUrl: 'https://status.fathom.video/',
    title: 'System Operational Status & Uptime | Fathom',
    description: 'Real-time operational status, 90-day component uptime history, and incident notifications. Sample status data.',
    status: 'built',
  },
  {
    path: '/terms',
    template: 'Company',
    tier: 2,
    originalUrl: 'https://fathom.ai/terms',
    title: 'Terms of Service | Fathom',
    description: 'Standard terms governing use of Fathom meeting services and software. Demo text, not legal advice.',
    status: 'built',
  },
  {
    path: '/privacy',
    template: 'Company',
    tier: 2,
    originalUrl: 'https://fathom.ai/privacy',
    title: 'Privacy Policy & Data Rights | Fathom',
    description: 'Detailed explanation of how meeting audio, transcripts, and account telemetry are processed and stored. Demo text.',
    status: 'built',
  },

  // AUTH, ONBOARDING & FORMS
  {
    path: '/signup',
    template: 'Form',
    tier: 2,
    originalUrl: 'https://fathom.ai/signup',
    title: 'Create Your Free Fathom Account',
    description: 'Sign up in 30 seconds. Connect your calendar and start getting receipt-backed meeting summaries today.',
    status: 'built',
  },
  {
    path: '/login',
    template: 'Form',
    tier: 2,
    originalUrl: 'https://fathom.ai/login',
    title: 'Log In to Fathom',
    description: 'Access your recorded meetings, action items, team workspaces, and custom summary templates.',
    status: 'built',
  },
  {
    path: '/book-demo',
    template: 'Form',
    tier: 2,
    originalUrl: 'https://fathom.ai/book-demo',
    title: 'Schedule an Enterprise Walkthrough | Fathom',
    description: 'Talk with our solution engineers about SOC2 compliance, team seat management, and custom CRM mapping.',
    status: 'built',
  },
  {
    path: '/switch',
    template: 'Form',
    tier: 2,
    originalUrl: 'https://fathom.ai/switch',
    title: 'Switch to Fathom — Migration Concierge & Credits',
    description: 'Switching from Otter, Fireflies, or Gong? Well import your legacy notes and credit your remaining contract term.',
    status: 'built',
  },
  {
    path: '/careers',
    template: 'Careers',
    tier: 3,
    originalUrl: 'https://fathom.ai/careers',
    title: 'Careers at Fathom — Join Our Engineering Team',
    description: 'We are building the future of truthful conversational intelligence. Explore open engineering, design, and product roles. Sample listings.',
    status: 'built',
  },
  {
    path: '/news/sample-announcement',
    template: 'Article',
    tier: 3,
    originalUrl: 'https://fathom.ai/news/superhuman-announcement',
    title: 'Sample Milestone Announcement: Next-Generation Audio Diarization',
    description: 'Announcing our latest multi-speaker audio separation benchmark and model updates. Sample announcement.',
    status: 'built',
  },

  // DEV & VERIFICATION PAGES
  {
    path: '/dev/parity',
    template: 'System',
    tier: 1,
    originalUrl: 'internal://parity-contract',
    title: 'Parity Contract & Route Verification Board | Fathom Rebuild',
    description: 'Live inventory table mapping every original fathom.ai and fathom.video URL to rebuilt demo routes with verification status.',
    status: 'built',
  },
  {
    path: '/dev/design',
    template: 'System',
    tier: 1,
    originalUrl: 'internal://design-gallery',
    title: 'Design System & Component Gallery | Fathom',
    description: 'Comprehensive token swatches, typography scales, tactile broadcast controls, and UI primitives.',
    status: 'verified',
  },
  {
    path: '/dev/recap-email',
    template: 'System',
    tier: 1,
    originalUrl: 'internal://recap-email',
    title: 'Recap Email Template Preview | Fathom',
    description: 'Responsive HTML email deliverable showing spoken receipts and action items sent immediately post-call.',
    status: 'verified',
  },

  // CORE APP & TIER B FEATURES
  {
    path: '/meetings',
    template: 'App',
    tier: 'App',
    originalUrl: 'https://app.fathom.video/meetings',
    title: 'Meetings Library | Fathom App',
    description: 'All recorded meetings, processing states, filterable views, and instant keyword and semantic search.',
    status: 'verified',
  },
  {
    path: '/meetings/:id',
    template: 'App',
    tier: 'App',
    originalUrl: 'https://app.fathom.video/meetings/showpiece',
    title: 'Flagship Meeting — 8-Person Roadmap Review | Fathom App',
    description: 'Full interactive 58-minute meeting with 8-lane Score timeline, binary-search transcript, and receipt-backed summary.',
    status: 'verified',
  },
  {
    path: '/live',
    template: 'App',
    tier: 'App',
    originalUrl: 'https://app.fathom.video/live',
    title: 'Live Call Recording Simulation | Fathom App',
    description: 'Streaming conversation turns, auto-stamped scratchpad, active speaker tally, and 1-click highlight flagging.',
    status: 'verified',
  },
  {
    path: '/settings',
    template: 'App',
    tier: 'App',
    originalUrl: 'https://app.fathom.video/settings',
    title: 'Workspace Settings & Recording Rules | Fathom App',
    description: 'Natural language automation rules, bot presence preferences, and calendar connection toggles.',
    status: 'verified',
  },
  {
    path: '/s/:token',
    template: 'App',
    tier: 'App',
    originalUrl: 'https://fathom.video/s/sample-share-token',
    title: 'Shared Meeting Recording (No Login Required)',
    description: 'Public zero-friction recipient view of meeting video, transcript, and key takeaways.',
    status: 'verified',
  },
  {
    path: '/app/templates',
    template: 'App',
    tier: 3,
    originalUrl: 'https://app.fathom.video/templates',
    title: 'Summary Templates Library & Visual Builder | Fathom App',
    description: '12 tailored meeting summary templates with live preview on showpiece call and custom section builder.',
    status: 'built',
  },
  {
    path: '/app/deals',
    template: 'App',
    tier: 3,
    originalUrl: 'https://app.fathom.video/deals',
    title: 'Deal Intelligence & Account Timelines | Fathom App',
    description: 'Chronological sales call timeline, AI deal summary, key stakeholder chips, and risks with receipts.',
    status: 'built',
  },
  {
    path: '/app/scorecards',
    template: 'App',
    tier: 3,
    originalUrl: 'https://app.fathom.video/scorecards',
    title: 'Rep Scorecards & MEDDIC Coaching | Fathom App',
    description: 'Objective criteria-based evaluation of sales discovery and qualification with audio evidence.',
    status: 'built',
  },
  {
    path: '/app/trackers',
    template: 'App',
    tier: 3,
    originalUrl: 'https://app.fathom.video/trackers',
    title: 'Keyword & Competitor Trackers | Fathom App',
    description: 'Natural language alert rules and chronological match feed with mini-Score visual indicators.',
    status: 'built',
  },
  {
    path: '/app/highlights',
    template: 'App',
    tier: 3,
    originalUrl: 'https://app.fathom.video/highlights',
    title: 'Clips & Playlist Compilation | Fathom App',
    description: 'Curate customer voice reels and objection playlists into a single shareable link.',
    status: 'built',
  },
  {
    path: '/app/analytics',
    template: 'App',
    tier: 3,
    originalUrl: 'https://app.fathom.video/analytics',
    title: 'Team Talk-Time & Meeting Analytics | Fathom App',
    description: 'Talk-to-listen ratios, longest monologues, question frequency, and pacing insights computed from speaker segments.',
    status: 'built',
  },
  {
    path: '/app/points',
    template: 'App',
    tier: 3,
    originalUrl: 'https://app.fathom.video/points',
    title: 'Referral Rewards & Balance | Fathom App',
    description: 'Personal referral link, rewards balance, and sample perks catalog.',
    status: 'built',
  },
  {
    path: '/calendar',
    template: 'App',
    tier: 1,
    originalUrl: 'https://app.fathom.video/calendar',
    title: 'Calendar Integration & Recording Rules | Fathom App',
    description: 'Connected calendar schedule, upcoming meetings, attendee domain classification, and per-meeting recording toggles.',
    status: 'verified',
    notes: 'Interactive calendar view connected to backend API with live record switches.',
  },
];
