import type { SummaryTemplateItem } from './types';

export const SUMMARY_TEMPLATES: SummaryTemplateItem[] = [
  {
    id: 'standard',
    name: 'Standard Meeting Recap',
    audience: 'General Teams & All-Hands',
    tone: 'Crisp, objective, and executive-level',
    description: 'High-signal 60-second summary separating key decisions from active follow-up items.',
    sections: [
      { heading: 'Key Decisions & Outcomes', instruction: 'List major decisions confirmed by attendees with exact timecode receipts.', format: 'bullets' },
      { heading: 'Action Items & Owners', instruction: 'Extract explicit verbal commitments including assigned owner and mentioned deadlines.', format: 'checklist' },
      { heading: 'Notable Discussion Points', instruction: 'Summarize core themes debated, trade-offs evaluated, and context.', format: 'bullets' },
    ],
  },
  {
    id: 'sales-discovery',
    name: 'Sales Discovery & Qualification',
    audience: 'Account Executives & Sales Management',
    tone: 'Commercial, direct, and outcome-oriented',
    description: 'Extracts prospect pain points, current workflow friction, budget parameters, and decision criteria.',
    sections: [
      { heading: 'Prospect Pain & Current Stack', instruction: 'Identify the exact workflow problems and tools currently used by the prospect.', format: 'bullets' },
      { heading: 'Budget & Commercial Authority', instruction: 'Extract confirmed budget figures, economic buyer identity, and fiscal constraints.', format: 'table' },
      { heading: 'Agreed Next Steps & Demo Scope', instruction: 'Document commitments made for technical evaluation or proposal presentation.', format: 'checklist' },
    ],
  },
  {
    id: 'sales-meddic',
    name: 'Sales Deal Review (MEDDIC)',
    audience: 'Revenue Operations & Sales Leadership',
    tone: 'Analytical and rigorous',
    description: 'Structured enterprise qualification across Metrics, Economic Buyer, Decision Criteria, Decision Process, Identified Pain, and Champion.',
    sections: [
      { heading: 'Metrics & Economic Impact', instruction: 'Quantifiable business targets (e.g. latency reduction, cost savings, revenue targets).', format: 'table' },
      { heading: 'Economic Buyer & Decision Process', instruction: 'Who controls the budget and what legal/procurement steps are required for sign-off.', format: 'bullets' },
      { heading: 'Decision Criteria & Competitors', instruction: 'Technical and business benchmarks, plus competitor vendors mentioned.', format: 'bullets' },
      { heading: 'Identified Pain & Champion', instruction: 'Specific operational roadblocks and who inside the account is advocating for Fathom.', format: 'bullets' },
    ],
  },
  {
    id: 'cs-checkin',
    name: 'Customer Success Check-In',
    audience: 'CSMs & Account Managers',
    tone: 'Empathetic and relationship-focused',
    description: 'Tracks customer health, platform adoption, open support tickets, and expansion opportunities.',
    sections: [
      { heading: 'Account Health & Sentiment', instruction: 'Assess overall satisfaction, team sentiment, and recent adoption hurdles.', format: 'bullets' },
      { heading: 'Feature Feedback & Escalations', instruction: 'List specific product feedback, bug reports, or feature requests made by the client.', format: 'bullets' },
      { heading: 'Renewal & Expansion Signals', instruction: 'Identify seat growth requests, upcoming renewal timelines, or contraction risks.', format: 'table' },
      { heading: 'Agreed Action Items', instruction: 'Customer and CSM commitments with direct audio receipts.', format: 'checklist' },
    ],
  },
  {
    id: 'qbr',
    name: 'Quarterly Business Review (QBR)',
    audience: 'Executive Sponsors & Business Leaders',
    tone: 'Strategic, metric-driven, and forward-looking',
    description: 'High-level executive review of past quarter ROI, joint accomplishments, and strategic goals for next quarter.',
    sections: [
      { heading: 'Executive Summary & ROI Delivered', instruction: 'Summarize total hours saved, adoption velocity, and key milestones accomplished.', format: 'prose' },
      { heading: 'Strategic Priorities for Next Quarter', instruction: 'Document joint goals, new integration rollouts, and organizational expansion plans.', format: 'bullets' },
      { heading: 'Contract & Governance Review', instruction: 'Review licensing terms, data residency compliance, and procurement timelines.', format: 'table' },
    ],
  },
  {
    id: 'product-discovery',
    name: 'Product Discovery & User Research',
    audience: 'Product Managers, UX Researchers, Designers',
    tone: 'Observational and verbatim-focused',
    description: 'Captures user workflows, usability friction, emotional reactions, and direct customer quotes with receipts.',
    sections: [
      { heading: 'Observed Workflow & Core Jobs-to-be-Done', instruction: 'What was the user attempting to accomplish and how did they navigate the interface?', format: 'bullets' },
      { heading: 'Verbatim Quotes & Sentiment', instruction: 'Extract powerful, unaltered user quotes accompanied by speaker and timecode receipts.', format: 'bullets' },
      { heading: 'Usability Friction & Blockers', instruction: 'Specific UI stumbling blocks, confusing terminology, or missing affordances.', format: 'bullets' },
      { heading: 'Feature Suggestions & Desired Behavior', instruction: 'Explicit ideas and workarounds suggested by the research participant.', format: 'bullets' },
    ],
  },
  {
    id: 'one-to-one',
    name: 'One-to-One (1:1) Sync',
    audience: 'Managers and Direct Reports',
    tone: 'Supportive, transparent, and growth-oriented',
    description: 'Structured manager-report check-in balancing immediate blockers with career development.',
    sections: [
      { heading: 'Priorities & Immediate Blockers', instruction: 'Current sprint deliverables, cross-functional dependencies, and urgent roadblocks.', format: 'bullets' },
      { heading: 'Feedback & Career Development', instruction: 'Discussion regarding performance, personal growth, learning goals, and wellness.', format: 'bullets' },
      { heading: 'Mutual Commitments', instruction: 'Tasks promised by both the manager and direct report before next sync.', format: 'checklist' },
    ],
  },
  {
    id: 'candidate-interview',
    name: 'Candidate Interview & Assessment',
    audience: 'Hiring Managers & Recruiting Teams',
    tone: 'Objective, evidence-based, and structured',
    description: 'Standardized candidate debrief evaluating technical depth, culture contribution, and role competencies.',
    sections: [
      { heading: 'Competency & Technical Evidence', instruction: 'Extract candidates specific answers to technical or architectural challenges with receipts.', format: 'bullets' },
      { heading: 'Leadership & Collaboration Style', instruction: 'Candidate responses to conflict resolution, cross-team communication, and ownership.', format: 'bullets' },
      { heading: 'Candidate Questions & Motivation', instruction: 'What questions did the candidate ask about team culture, strategy, and tech stack?', format: 'bullets' },
      { heading: 'Hiring Recommendation Scorecard', instruction: 'Overall impression against rubric criteria with direct spoken evidence.', format: 'table' },
    ],
  },
  {
    id: 'team-standup',
    name: 'Team Standup & Daily Sync',
    audience: 'Engineering & Agile Teams',
    tone: 'Fast, concise, and focused on momentum',
    description: 'Captures yesterday completed deliverables, today focus, and immediate cross-team blockers.',
    sections: [
      { heading: 'Completed Yesterday', instruction: 'Shipped PRs, completed designs, and resolved tickets.', format: 'checklist' },
      { heading: 'In Progress Today', instruction: 'Active tasks and focal points for each individual speaker.', format: 'checklist' },
      { heading: 'Blockers & Help Needed', instruction: 'Dependencies requiring peer pairing or managerial unblocking.', format: 'bullets' },
    ],
  },
  {
    id: 'marketing-brainstorm',
    name: 'Marketing Brainstorm & Creative Sync',
    audience: 'Creative Directors, Copywriters, Growth Leads',
    tone: 'Generative, expansive, and high-energy',
    description: 'Catalogs campaign concepts, messaging angles, audience hooks, and experimental tactics.',
    sections: [
      { heading: 'Top Campaign Angles & Hooks', instruction: 'Creative ideas and framing proposed during the brainstorming session.', format: 'bullets' },
      { heading: 'Content & Channel Experiments', instruction: 'Specific distribution channels, formats, and creative deliverables considered.', format: 'bullets' },
      { heading: 'Actionable Next Steps & Assignments', instruction: 'Who will draft creative briefs or build landing page experiments.', format: 'checklist' },
    ],
  },
  {
    id: 'project-kickoff',
    name: 'Project Kickoff & Alignment',
    audience: 'Cross-Department Project Leads & Stakeholders',
    tone: 'Clear, foundational, and milestone-driven',
    description: 'Establishes project scope, key milestones, RACI ownership, and communication cadence.',
    sections: [
      { heading: 'Project Scope & Non-Goals', instruction: 'Document agreed scope boundaries and explicitly what is out of scope for v1.', format: 'bullets' },
      { heading: 'Target Milestones & Schedule', instruction: 'Agreed delivery dates, beta launch windows, and review checkpoints.', format: 'table' },
      { heading: 'RACI Ownership Matrix', instruction: 'Who is Responsible, Accountable, Consulted, and Informed for each deliverable.', format: 'table' },
    ],
  },
  {
    id: 'retrospective',
    name: 'Sprint Retrospective & Post-Mortem',
    audience: 'Sprint Teams & Agile Coaches',
    tone: 'Constructive, blameless, and iterative',
    description: 'Evaluates what went well, what could be improved, and actionable experiments for the next sprint.',
    sections: [
      { heading: 'What Went Well (Celebrate Wins)', instruction: 'Highlight successful launches, good collaboration, and velocity improvements.', format: 'bullets' },
      { heading: 'What Could Be Improved (Friction Points)', instruction: 'Document bottlenecks, technical debt, or communication breakdowns observed.', format: 'bullets' },
      { heading: 'Sprint Action Items & Process Experiments', instruction: 'Specific operational changes the team commits to testing in the upcoming cycle.', format: 'checklist' },
    ],
  },
];
